<?php

use App\Http\Controllers\BackupController;
use App\Http\Controllers\CloudAccountController;
use App\Http\Controllers\CloudAuthController;
use App\Http\Controllers\ClusterAccessController;
use App\Http\Controllers\ClusterToolController;
use App\Http\Controllers\CompanionController;
use App\Http\Controllers\ContextController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DevBoxController;
use App\Http\Controllers\DiagnosticsController;
use App\Http\Controllers\LocalSetupController;
use App\Http\Controllers\MailController;
use App\Http\Controllers\OpenExternalController;
use App\Http\Controllers\PlexController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\ProjectDotenvController;
use App\Http\Controllers\ProjectScalingController;
use App\Http\Controllers\QuickActionController;
use App\Http\Controllers\ReadinessController;
use App\Http\Controllers\RunController;
use App\Http\Controllers\ServerController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\ToolInstallController;
use App\Http\Controllers\UpdatesController;
use App\Http\Controllers\WorkspaceController;
use App\Http\Controllers\WslSetupController;
use Illuminate\Support\Facades\Route;

Route::get('/', [DashboardController::class, 'index'])->name('home');
Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

Route::get('/readiness', [ReadinessController::class, 'show'])->name('readiness');
Route::post('/setup/cli/update', [ToolInstallController::class, 'updateCli'])->name('setup.cli.update');
Route::post('/setup/tools/{tool}/install', [ToolInstallController::class, 'store'])->name('setup.tools.install');
Route::get('/setup/tools/{tool}/status', [ReadinessController::class, 'toolStatus'])->name('setup.tools.status');
Route::post('/setup/wsl/{step}', [WslSetupController::class, 'store'])->whereIn('step', ['enable', 'download', 'import', 'reset'])->name('setup.wsl');
Route::post('/setup/local', [LocalSetupController::class, 'store'])->name('setup.local');
Route::post('/setup/terminal/install', [ReadinessController::class, 'installTerminal'])->name('setup.terminal.install');
Route::post('/setup/usage', [ReadinessController::class, 'setUsage'])->name('setup.usage');
Route::post('/setup/cli/channel', [ReadinessController::class, 'setChannel'])->name('setup.cli.channel');
Route::post('/setup/cloud/aws', [CloudAuthController::class, 'saveAws'])->name('setup.cloud.aws');
Route::post('/setup/cloud/gcp/login', [CloudAuthController::class, 'loginGcp'])->name('setup.cloud.gcp.login');
Route::get('/setup/cloud/gcp/login/{run}', [CloudAuthController::class, 'gcpLoginStatus'])->name('setup.cloud.gcp.login.status');
Route::post('/setup/cloud/gcp/login/{run}/code', [CloudAuthController::class, 'gcpLoginCode'])->name('setup.cloud.gcp.login.code');
Route::get('/setup/cloud/gcp/projects', [CloudAuthController::class, 'gcpProjects'])->name('setup.cloud.gcp.projects');
Route::post('/setup/cloud/gcp/project', [CloudAuthController::class, 'setGcpProject'])->name('setup.cloud.gcp.project');
Route::post('/setup/cloud/accounts/default', [CloudAccountController::class, 'setDefault'])->name('setup.cloud.accounts.default');
Route::post('/setup/cloud/accounts', [CloudAccountController::class, 'add'])->name('setup.cloud.accounts.add');
Route::delete('/setup/cloud/accounts', [CloudAccountController::class, 'remove'])->name('setup.cloud.accounts.remove');

Route::get('/servers', [ServerController::class, 'index'])->name('servers.index');
Route::get('/servers/create', [ServerController::class, 'create'])->name('servers.create');
Route::post('/servers', [ServerController::class, 'store'])->name('servers.store');

Route::pattern('server', '[a-z0-9][a-z0-9-]*');
Route::pattern('tool', '[a-z][a-z0-9-]*');

Route::get('/servers/health', [ServerController::class, 'health'])->name('servers.health');
Route::get('/servers/{server}', [ServerController::class, 'show'])->name('servers.show');
Route::delete('/servers/{server}', [ServerController::class, 'destroy'])->name('servers.destroy');
Route::post('/servers/{server}/restart', [ServerController::class, 'restart'])->name('servers.restart');
Route::post('/servers/{server}/dns', [ServerController::class, 'connectDomain'])->name('servers.dns');
Route::post('/servers/{server}/tls', [ServerController::class, 'enableSsl'])->name('servers.tls');
Route::post('/servers/{server}/plex/init', [PlexController::class, 'initServer'])->name('servers.plex.init');
Route::post('/servers/{server}/plex/start', [PlexController::class, 'startServer'])->name('servers.plex.start');
Route::post('/servers/{server}/plex/stop', [PlexController::class, 'stopServer'])->name('servers.plex.stop');
Route::post('/servers/{server}/backups/setup', [BackupController::class, 'setup'])->name('servers.backups.setup');
Route::post('/servers/{server}/backups/schedule', [BackupController::class, 'schedule'])->name('servers.backups.schedule');
Route::post('/servers/{server}/backups/unschedule', [BackupController::class, 'unschedule'])->name('servers.backups.unschedule');
Route::post('/servers/{server}/backups/run', [BackupController::class, 'run'])->name('servers.backups.run');
Route::post('/servers/{server}/backups/check', [BackupController::class, 'check'])->name('servers.backups.check');
Route::post('/servers/{server}/backups/restore', [BackupController::class, 'restore'])->name('servers.backups.restore');
Route::post('/servers/{server}/backups/prune', [BackupController::class, 'prune'])->name('servers.backups.prune');
Route::post('/servers/{server}/backups/recovery-card', [BackupController::class, 'recoveryCard'])->name('servers.backups.recovery-card');
Route::post('/servers/{server}/access/grant', [ClusterAccessController::class, 'grant'])->name('servers.access.grant');
Route::post('/servers/{server}/access/revoke', [ClusterAccessController::class, 'revoke'])->name('servers.access.revoke');

Route::get('/dev-boxes', [DevBoxController::class, 'index'])->name('devboxes.index');
Route::get('/dev-boxes/pick-bundle', [DevBoxController::class, 'pickBundle'])->name('devboxes.pick-bundle');
Route::post('/dev-boxes/import', [DevBoxController::class, 'import'])->name('devboxes.import');
Route::get('/dev-boxes/create', [DevBoxController::class, 'create'])->name('devboxes.create');
Route::post('/dev-boxes', [DevBoxController::class, 'store'])->name('devboxes.store');
Route::get('/dev-boxes/{box}', [DevBoxController::class, 'show'])->name('devboxes.show');
Route::post('/dev-boxes/{box}/export', [DevBoxController::class, 'export'])->name('devboxes.export');
Route::post('/dev-boxes/{box}/access/grant', [DevBoxController::class, 'grant'])->name('devboxes.access.grant');
Route::post('/dev-boxes/{box}/access/revoke', [DevBoxController::class, 'revoke'])->name('devboxes.access.revoke');
Route::post('/dev-boxes/{box}/update-cli', [DevBoxController::class, 'updateCli'])->name('devboxes.update-cli');
Route::get('/dev-boxes/{box}/projects/{project}', [DevBoxController::class, 'showProject'])->where('project', '[a-z0-9][a-z0-9-]*')->name('devboxes.projects.show');
Route::post('/dev-boxes/{box}/projects/{project}/{action}', [DevBoxController::class, 'operate'])->where('project', '[a-z0-9][a-z0-9-]*')->where('action', 'up|down|start|stop|deploy')->name('devboxes.operate');
Route::post('/dev-boxes/{box}/projects/{project}/environments', [DevBoxController::class, 'addEnvironment'])->where('project', '[a-z0-9][a-z0-9-]*')->name('devboxes.projects.environments.store');
Route::post('/dev-boxes/{box}/projects/{project}/scaling/replicas', [DevBoxController::class, 'scaleReplicas'])->where('project', '[a-z0-9][a-z0-9-]*')->name('devboxes.projects.scaling.replicas');
Route::post('/dev-boxes/{box}/projects/{project}/scaling/autoscale', [DevBoxController::class, 'scaleAutoscale'])->where('project', '[a-z0-9][a-z0-9-]*')->name('devboxes.projects.scaling.autoscale');
Route::post('/dev-boxes/{box}/projects/{project}/scaling/resources', [DevBoxController::class, 'scaleResources'])->where('project', '[a-z0-9][a-z0-9-]*')->name('devboxes.projects.scaling.resources');
Route::get('/dev-boxes/{box}/projects/{project}/dotenv/status', [DevBoxController::class, 'dotenvStatus'])->where('project', '[a-z0-9][a-z0-9-]*')->name('devboxes.projects.dotenv.status');
Route::post('/dev-boxes/{box}/projects/{project}/dotenv/push', [DevBoxController::class, 'dotenvPush'])->where('project', '[a-z0-9][a-z0-9-]*')->name('devboxes.projects.dotenv.push');
Route::post('/dev-boxes/{box}/projects/{project}/dotenv/pull', [DevBoxController::class, 'dotenvPull'])->where('project', '[a-z0-9][a-z0-9-]*')->name('devboxes.projects.dotenv.pull');
Route::get('/dev-boxes/{box}/projects/{project}/share-domain', [DevBoxController::class, 'shareDomainPage'])->where('project', '[a-z0-9][a-z0-9-]*')->name('devboxes.share-domain-page');
Route::post('/dev-boxes/{box}/domains', [DevBoxController::class, 'domains'])->name('devboxes.domains');
Route::post('/dev-boxes/{box}/projects/{project}/share-domain', [DevBoxController::class, 'shareDomain'])->where('project', '[a-z0-9][a-z0-9-]*')->name('devboxes.share-domain');
Route::delete('/dev-boxes/{box}/projects/{project}/share-domain', [DevBoxController::class, 'removeDomain'])->where('project', '[a-z0-9][a-z0-9-]*')->name('devboxes.remove-domain');

Route::pattern('box', '[a-z0-9][a-z0-9-]*');
Route::pattern('workspace', '[a-z0-9][a-z0-9-]*');
Route::get('/workspaces', [WorkspaceController::class, 'index'])->name('workspaces.index');
Route::post('/workspaces', [WorkspaceController::class, 'store'])->name('workspaces.store');
Route::post('/workspaces/{workspace}/suspend', [WorkspaceController::class, 'suspend'])->name('workspaces.suspend');
Route::post('/workspaces/{workspace}/resume', [WorkspaceController::class, 'resume'])->name('workspaces.resume');
Route::post('/workspaces/{workspace}/open', [WorkspaceController::class, 'open'])->name('workspaces.open');
Route::delete('/workspaces/{workspace}', [WorkspaceController::class, 'destroy'])->name('workspaces.destroy');

Route::get('/projects', [ProjectController::class, 'index'])->name('projects.index');
Route::post('/projects', [ProjectController::class, 'store'])->name('projects.store');
Route::post('/projects/clone', [ProjectController::class, 'clone'])->name('projects.clone');
Route::post('/projects/clone/dev-box', [ProjectController::class, 'cloneOnDevBox'])->name('projects.clone-dev-box');
Route::post('/projects/pick-folder', [ProjectController::class, 'pickParentFolder'])->name('projects.pick-folder');
Route::get('/projects/create', [ProjectController::class, 'create'])->name('projects.create');
Route::post('/projects/create/folder', [ProjectController::class, 'chooseFolder'])->name('projects.choose-folder');
Route::post('/projects/create', [ProjectController::class, 'scaffold'])->name('projects.scaffold');
Route::post('/projects/create/dev-box', [ProjectController::class, 'scaffoldOnDevBox'])->name('projects.scaffold-dev-box');
Route::post('/projects/local/stop-all', [ProjectController::class, 'stopAll'])->name('projects.stop-all');
Route::post('/projects/local/down-all', [ProjectController::class, 'downAll'])->name('projects.down-all');
Route::get('/projects/{project}', [ProjectController::class, 'show'])->name('projects.show');
Route::delete('/projects/{project}', [ProjectController::class, 'destroy'])->name('projects.destroy');
Route::post('/projects/{project}/init', [ProjectController::class, 'init'])->name('projects.init');
Route::post('/projects/{project}/link', [ProjectController::class, 'link'])->name('projects.link');
Route::post('/projects/{project}/host', [ProjectController::class, 'host'])->name('projects.host');
Route::post('/projects/{project}/ci', [ProjectController::class, 'configureCi'])->name('projects.ci');
Route::post('/projects/{project}/retry', [ProjectController::class, 'retry'])->name('projects.retry');
Route::post('/projects/{project}/folder', [ProjectController::class, 'showFolder'])->name('projects.folder');
Route::post('/projects/{project}/editor', [ProjectController::class, 'openInEditor'])->name('projects.editor');
Route::post('/projects/{project}/deploy', [ProjectController::class, 'deploy'])->name('projects.deploy');
Route::post('/projects/{project}/up', [ProjectController::class, 'up'])->name('projects.up');
Route::post('/projects/{project}/down', [ProjectController::class, 'down'])->name('projects.down');
Route::post('/projects/{project}/start', [ProjectController::class, 'start'])->name('projects.start');
Route::post('/projects/{project}/stop', [ProjectController::class, 'stop'])->name('projects.stop');
Route::post('/projects/{project}/tld', [ProjectController::class, 'tld'])->name('projects.tld');
Route::post('/projects/{project}/plex/join', [PlexController::class, 'joinProject'])->name('projects.plex.join');
Route::get('/projects/{project}/services', [ProjectController::class, 'services'])->name('projects.services');
Route::post('/projects/{project}/plex/leave', [PlexController::class, 'leaveProject'])->name('projects.plex.leave');
Route::post('/projects/{project}/scaling/replicas', [ProjectScalingController::class, 'updateReplicas'])->name('projects.scaling.replicas');
Route::post('/projects/{project}/scaling/autoscale', [ProjectScalingController::class, 'updateAutoscale'])->name('projects.scaling.autoscale');
Route::post('/projects/{project}/scaling/resources', [ProjectScalingController::class, 'updateResources'])->name('projects.scaling.resources');
Route::get('/projects/{project}/dotenv/status', [ProjectDotenvController::class, 'status'])->name('projects.dotenv.status');
Route::post('/projects/{project}/dotenv/push', [ProjectDotenvController::class, 'push'])->name('projects.dotenv.push');
Route::post('/projects/{project}/dotenv/pull', [ProjectDotenvController::class, 'pull'])->name('projects.dotenv.pull');

Route::get('/mail', [MailController::class, 'entry'])->name('mail');
Route::get('/servers/{server}/mail', [MailController::class, 'index'])->name('servers.mail.index');
Route::post('/servers/{server}/mail/deploy', [MailController::class, 'deploy'])->name('servers.mail.deploy');
Route::post('/servers/{server}/mail/accounts', [MailController::class, 'createAccount'])->name('servers.mail.accounts.store');
Route::post('/servers/{server}/mail/accounts/password', [MailController::class, 'resetPassword'])->name('servers.mail.accounts.password');
Route::post('/servers/{server}/mail/sync-sso', [MailController::class, 'syncSso'])->name('servers.mail.sync-sso');
Route::delete('/servers/{server}/mail/accounts', [MailController::class, 'deleteAccount'])->name('servers.mail.accounts.destroy');
Route::post('/servers/{server}/mail/domains', [MailController::class, 'addDomain'])->name('servers.mail.domains.store');
Route::post('/servers/{server}/mail/relay', [MailController::class, 'configureRelay'])->name('servers.mail.relay.store');
Route::post('/servers/{server}/mail/test', [MailController::class, 'sendTest'])->name('servers.mail.test');
Route::get('/servers/{server}/mail/check-dns', [MailController::class, 'checkDns'])->name('servers.mail.check-dns');

Route::get('/tools', [ClusterToolController::class, 'entry'])->name('tools');
Route::get('/servers/{server}/tools', [ClusterToolController::class, 'index'])->name('servers.tools.index');
Route::get('/servers/{server}/check-dns', [ClusterToolController::class, 'checkDns'])->name('servers.tools.check-dns');
Route::post('/servers/{server}/tools/refresh', [ClusterToolController::class, 'refresh'])->name('servers.tools.refresh');
Route::get('/servers/{server}/tools/{tool}', [ClusterToolController::class, 'show'])->name('servers.tools.show');
Route::post('/servers/{server}/tools/{tool}', [ClusterToolController::class, 'store'])->name('servers.tools.store');
Route::delete('/servers/{server}/tools/{tool}', [ClusterToolController::class, 'destroy'])->name('servers.tools.destroy');
Route::post('/quick-actions/launch', [QuickActionController::class, 'launch'])->name('quick-actions.launch');

Route::post('/companions/add', [CompanionController::class, 'add'])->name('companions.add');
Route::post('/companions/remove', [CompanionController::class, 'remove'])->name('companions.remove');
Route::post('/companions/start', [CompanionController::class, 'start'])->name('companions.start');
Route::post('/companions/stop', [CompanionController::class, 'stop'])->name('companions.stop');

Route::match(['get', 'post'], '/context/pick-file', [ContextController::class, 'pickFile'])->name('context.pick-file');
Route::post('/context/import', [ContextController::class, 'import'])->name('context.import');
Route::post('/context/switch', [ContextController::class, 'switchContext'])->name('context.switch');
Route::post('/context/backup', [ContextController::class, 'backup'])->name('context.backup');
Route::post('/context/restore', [ContextController::class, 'restore'])->name('context.restore');
Route::post('/context/remove', [ContextController::class, 'remove'])->name('context.remove');

Route::get('/diagnostics', DiagnosticsController::class)->name('diagnostics');
Route::post('/diagnostics/folder', [DiagnosticsController::class, 'folder'])->name('diagnostics.folder');
Route::get('/updates', [UpdatesController::class, 'status'])->name('updates.status');
Route::post('/updates/check', [UpdatesController::class, 'check'])->name('updates.check');
Route::post('/updates/install', [UpdatesController::class, 'install'])->name('updates.install');
Route::get('/settings', [SettingsController::class, 'show'])->name('settings.show');
Route::post('/settings', [SettingsController::class, 'update'])->name('settings.update');
Route::post('/settings/theme', [SettingsController::class, 'setTheme'])->name('settings.theme');
Route::post('/settings/bridge/{agent}', [SettingsController::class, 'bridge'])->name('settings.bridge');

Route::post('/open', OpenExternalController::class)->name('open');

Route::get('/runs', [RunController::class, 'index'])->name('runs.index');
Route::get('/runs/{run}', [RunController::class, 'show'])->name('runs.show');
Route::get('/runs/{run}/stream', [RunController::class, 'stream'])->name('runs.stream');
Route::post('/runs/{run}/detach', [RunController::class, 'detach'])->name('runs.detach');
Route::post('/runs/{run}/cancel', [RunController::class, 'cancel'])->name('runs.cancel');
Route::post('/runs/{run}/reveal', [RunController::class, 'reveal'])->name('runs.reveal');
Route::get('/runs/{run}/file', [RunController::class, 'fileContent'])->name('runs.file');
